### ISSUE TITLE
Fatal crash when running

### ISSUE THREAD

**Issue by alekslyse** [akopulko/ffiiitc#7]
I am experiencing a fatal crash loading up this program. It cam connect to firefly iii as I see its loading the transactions. Then it crashes with
`panic: provide at least two classes
goroutine 1 [running]:
github.com/navossoc/bayesian.NewClassifier(...)
	/go/pkg/mod/github.com/navossoc/bayesian@v0.0.0-20230423142728-ab66f8feaf97/bayesian.go:136
ffiiitc/internal/classifier.trainClassifierFromTransactions({0xc0001cc000?, 0x804448?, 0x1152d4bab7108?})
	/src/internal/classifier/classifier.go:95 +0x50d
ffiiitc/internal/classifier.NewTrnClassifier(0xc000000180?, 0xc000000180)
	/src/internal/classifier/classifier.go:38 +0x1a5
main.main()
	/src/main.go:37 +0x1ba`

After this its not making the model file, and just loop

**Comment by akopulko** [comment]
can you please post here logs from container where fftc is running? Thanks!
